version: '3.9'

services:
  react:
    build: .
    ports:
      - "5734:80"  
    depends_on:
      - flask  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - ./.env

  flask:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env

